### ISSUE TITLE
Permit 1 character room name

### ISSUE THREAD

**Issue by rulojuka** [yancouto/gfy-sim#12]
Is there a reason for [this regexp](https://github.com/yancouto/gfy-sim/blob/4672b495ea8b7677968d17e0420775411556eea2/src/client/gamestates/RoomMenu.js#L89)? I just spent 30 minutes trying to create the room "1" (and 0, and 2, and 3...) and thought the game was broken :)

If there is a reason, maybe an
```
else{
	console.log("Invalid room name or user name. Valid room names are between 2 and 20 in length. Valid user names are between 1 and 100 in length and do not contain commas");
}
```
would avoid some trouble for now!

**Comment by yancouto** [comment]
Allowed 1 letter room names, why not.
